yxb:
  age: 299
spring:
  datasource:
    url: jdbc:mysql://192.168.80.232:3306/xplat_1.0.5?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: kh9001
    driver-class-name: com.mysql.jdbc.Driver
