yxb:
  age: 299
server:
  port: 10001
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
        #- refresh
        #- health
        #- info
  endpoint:
      health:
        show-details: ALWAYS
spring:
  #rabbitmq配置 ，消息中间件，分布式总线配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://192.168.80.232:3306/xplat_1.0.5?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: kh9001
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: pv-netty-base
  zipkin:
    base-url: http://192.168.80.220:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
hystrix:
  metrics:
    polling-interval-ms: 20000
logging:
  config: classpath:logback-dev.xml
